# Generated by Django 3.1.1 on 2020-09-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_lparaprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='lparaprocess',
            name='appreciation_text',
            field=models.CharField(default='good', max_length=150),
            preserve_default=False,
        ),
    ]
